# 00 — Exploratory Data Analysis: Athletes

**Purpose**: Understand the raw `summerOly_athletes.csv` before writing cleaning code.
Each section checks one aspect of data quality. Findings feed directly into `src/preprocess/clean_athletes.py`.

Reference: PIPELINE.md Section 1.1

## 0. Setup

In [5]:
import sys
from pathlib import Path

import pandas as pd
import numpy as np

project_root = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
sys.path.insert(0, str(project_root))

from src.utils.config import ATHLETES_FILE, DATA_DICT_FILE
from src.utils.io_utils import read_csv

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 60)
pd.set_option('display.max_rows', 20)

print(f'Project root: {project_root}')
print(f'Data file  : {ATHLETES_FILE}')

Project root: d:\Vault\Future\2025_Problem_C
Data file  : D:\Vault\Future\2025_Problem_C\data\summerOly_athletes.csv

## 1. Basic Shape & Structure

**Why**: Confirm we have the expected 252,565 rows and 9 columns. Any deviation means the data file may have been corrupted or truncated.

In [6]:
df = read_csv(ATHLETES_FILE)

print(f'Rows: {df.shape[0]:,}')
print(f'Columns: {df.shape[1]}')
print()
print('Column list:')
for i, col in enumerate(df.columns):
    print(f'  [{i}] {col}')
print()
print('dtypes:')
print(df.dtypes)

Rows: 252,565
Columns: 9

Column list:
  [0] Name
  [1] Sex
  [2] Team
  [3] NOC
  [4] Year
  [5] City
  [6] Sport
  [7] Event
  [8] Medal

dtypes:
Name       str
Sex        str
Team       str
NOC        str
Year     int64
City       str
Sport      str
Event      str
Medal      str
dtype: object

## 2. Missing Values

**Why**: Missing values in `Medal` are expected (many athletes didn't win). Missing values in `NOC`, `Year`, or `Event` would indicate data corruption. Knowing which columns have NaN helps us design proper fill/drop logic in the cleaning script.

In [7]:
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

missing_df = pd.DataFrame({
    'missing_count': missing,
    'missing_pct': missing_pct
})
print(missing_df[missing_df['missing_count'] > 0])

Empty DataFrame
Columns: [missing_count, missing_pct]
Index: []

## 3. Sample Rows — Head, Tail, Random

**Why**: Visually inspect the data to spot obvious anomalies (garbled text, weird values, etc.). Random sampling shows rows that head/tail might miss.

In [8]:
print('=== HEAD (first 5) ===')
display(df.head())
print('\n=== TAIL (last 5) ===')
display(df.tail())
print('\n=== RANDOM (5 rows) ===')
display(df.sample(5, random_state=42))

=== HEAD (first 5) ===

,Name,Sex,Team,NOC,Year,City,Sport,Event,Medal
0,Ahmad Abouwi,M,Afghanistan,AFG,1956,Melbourne,Hockey,Hockey Men's Hockey,No medal
1,Jammal-ud-Din Affendi,M,Afghanistan,AFG,1936,Berlin,Hockey,Hockey Men's Hockey,No medal
2,Mohammad Afzal,M,Afghanistan,AFG,1948,London,Football,Football Men's Football,No medal
3,Mohammad Aktar,M,Afghanistan,AFG,1980,Moskva,Wrestling,"Wrestling Men's Light-Flyweight, Freestyle",No medal
4,Mohammad Anwary,M,Afghanistan,AFG,1964,Tokyo,Wrestling,"Wrestling Men's Bantamweight, Freestyle",No medal

=== TAIL (last 5) ===

,Name,Sex,Team,NOC,Year,City,Sport,Event,Medal
252560,Joan Nyahora,F,Zimbabwe,ZIM,2024,Paris,Athletics,Women's Marathon,No medal
252561,Isaac Mpofu,M,Zimbabwe,ZIM,2024,Paris,Athletics,Men's Marathon,No medal
252562,Makanakaishe Charamba,M,Zimbabwe,ZIM,2024,Paris,Athletics,Men's 200m,No medal
252563,van Paige,F,Zimbabwe,ZIM,2024,Paris,Swimming,Women's 100m Freestyle,No medal
252564,Denilson Cyprianos,M,Zimbabwe,ZIM,2024,Paris,Swimming,Men's 200m Backstroke,No medal

=== RANDOM (5 rows) ===

,Name,Sex,Team,NOC,Year,City,Sport,Event,Medal
200029,Lala Wane,F,Senegal,SEN,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,No medal
211421,Ingrid (-grane),F,Sweden,SWE,1952,Helsinki,Swimming,Swimming Women's 400 metres Freestyle,No medal
107366,Karin Schnaase,F,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Women's Singles,No medal
251058,Franjo Mihali,M,Yugoslavia,YUG,1952,Helsinki,Athletics,"Athletics Men's 10,000 metres",No medal
196023,Aleksandr Danilov,M,Russia,RUS,1996,Atlanta,Shooting,"Shooting Men's Free Pistol, 50 metres",No medal

## 4. Medal Values — Unique Check

**Why**: PIPELINE.md says valid values are {Gold, Silver, Bronze, No medal}. We need to see all *actual* values in the column to know what normalization is required (e.g. "No Medal" vs "No medal").

In [9]:
medal_vals = df['Medal'].value_counts(dropna=False)
print(f'Unique Medal values: {df["Medal"].nunique()}')
print()
for val, count in medal_vals.items():
    flag = ''
    if pd.isna(val):
        flag = ' <-- NaN'
    elif val not in {'Gold', 'Silver', 'Bronze', 'No medal'}:
        flag = ' <-- NEEDS NORMALIZATION'
    print(f'  [{val}] : {count:,}{flag}')

Unique Medal values: 4

  [No medal] : 213,747
  [Bronze] : 13,070
  [Gold] : 13,002
  [Silver] : 12,746

## 5. Year Distribution

**Why**: Confirm years are in [1896, 2024], every 4 years, and check for any anomalous years (e.g., cancelled years 1916/1940/1944 appearing). Knowing the year span tells us how many Olympiads we have data for.

In [10]:
from src.utils.config import CANCELLED_YEARS, OLYMPIC_YEARS

print(f'Year range: {df["Year"].min()} - {df["Year"].max()}')
print(f'Unique years in data: {sorted(df["Year"].unique())}')
print()

# Check for cancelled years
bad_years = set(df['Year'].unique()) & CANCELLED_YEARS
if bad_years:
    print(f'CANCELLED YEARS FOUND: {bad_years}')
else:
    print('No cancelled years in data')

# Rows per year
print('\nRows per Olympiad:')
display(df['Year'].value_counts().sort_index())

Year range: 1896 - 2024
Unique years in data: [np.int64(1896), np.int64(1900), np.int64(1904), np.int64(1906), np.int64(1908), np.int64(1912), np.int64(1920), np.int64(1924), np.int64(1928), np.int64(1932), np.int64(1936), np.int64(1948), np.int64(1952), np.int64(1956), np.int64(1960), np.int64(1964), np.int64(1968), np.int64(1972), np.int64(1976), np.int64(1980), np.int64(1984), np.int64(1988), np.int64(1992), np.int64(1996), np.int64(2000), np.int64(2004), np.int64(2008), np.int64(2012), np.int64(2016), np.int64(2020), np.int64(2024)]

No cancelled years in data

Rows per Olympiad:

Year
1896      380
1900     1936
1904     1301
1906     1733
1908     3101
        ...
2008    13602
2012    12920
2016    13688
2020    15121
2024    14892
Name: count, Length: 31, dtype: int64

## 6. NOC vs Team — The Critical Relationship

**Why**: This is the SINGLE most important check for Phase 1. The same NOC code can have multiple Team name spellings (e.g. 'United States' vs 'United States-1'). We need to discover all (NOC, Team) pairs to build the NOC unification table (Step 1.5).

Questions we answer:
- How many unique NOC codes?
- How many unique Team names?
- Which NOCs have multiple Team spellings?
- Which Team names contain a dash-suffix pattern (multi-team indicator)?

In [11]:
noc_team = df.groupby('NOC')['Team'].apply(lambda x: sorted(x.unique())).reset_index()
noc_team['n_team_names'] = noc_team['Team'].apply(len)

print(f'Unique NOC codes  : {df["NOC"].nunique()}')
print(f'Unique Team names : {df["Team"].nunique()}')
print()

# NOCs with multiple Team spellings - these need the unification table
multi_name = noc_team[noc_team['n_team_names'] > 1].sort_values('n_team_names', ascending=False)
print(f'NOCs with >1 Team spelling: {len(multi_name)}')
print()
print('=== Top 20 NOCs with most Team name variants ===')
for _, row in multi_name.head(20).iterrows():
    print(f'  {row["NOC"]} ({row["n_team_names"]}): {row["Team"]}')

Unique NOC codes  : 234
Unique Team names : 1193

NOCs with >1 Team spelling: 101

=== Top 20 NOCs with most Team name variants ===
  FRA (160): ['Alcyon-6', 'Alcyon-7', 'Allegro', 'Aloha II', 'Amulet-3', 'Amulet-7', 'Ariette-10', 'Ariette-8', 'Astrid III', 'BLO Polo Club, Rugby', 'Baby-1', 'Baby-9', 'Bagatelle Polo Club, Paris', 'C.V.A.-14', 'C.V.A.-7', 'Calimucho', 'Calypse II', 'Camille', 'Carabinier-15', 'Carabinier-5', 'Cercle Nautique de Reims-4', "Cercle de l'Aviron Roubaix-4", 'Chicago Athletic Association', 'Cinara-13', 'Club Nautique de Dieppe-5', 'Club Nautique de Franais-1', 'Club Nautique de Lyon-2', 'Colette-10', 'Colette-12', 'Compigne Polo Club', 'Crabe I-11', 'Crabe I-2', 'Crabe I-3', 'Crabe II-1', 'Crabe II-12', 'Crabe II-4', 'Crocodile-11', 'Crocodile-13', 'Cupidon Viking', 'Damoiselle', 'Demi-Mondaine-15', 'Demi-Mondaine-17', 'Diabolo St Maurice', 'Dick-8', 'Ducky-16', 'Ducky-4', 'EA II', 'Eissero VI', 'Esterel-1', 'Fada', 'Fantlet-2', 'Fantlet-7', 'Favorite-1', 'Favorite-17', 'Femur-1', 'Femur-18', 'France', 'France-1', 'France-2', 'France-3', 'France-4', 'France/Great Britain', 'Freia-19', 'Freia-5', 'Frip IV', 'Galopin-20', 'Galopin-9', 'Gam II', 'Gilliatt V', 'Giselle-6', 'Gitana-2', 'Gitana-21', 'Guyoni', 'Gwendoline-2', 'Gwendoline-22', 'Gyp-23', 'Gyp-6', 'Hb-20', 'Hb-24', 'Jeanette-25', 'Jeannette-18', 'Kannibaltje', "L'Aile VI", 'LaBandera', 'Leipzig', 'Libellule de Paris', 'Libellule de Paris-3', 'Mac Miche', 'Mamie-4', 'Mamie-6', 'Marsouin-26', 'Marsouin-8', 'Martha-1', 'Martha-27', 'Mascaret-28', 'Mascaret-4', 'Mignon-29', 'Mignon-3', 'Namoussa', 'Nina Claire-2', 'Nina Claire-30', 'Olle', 'Pettit-Poucet-6', 'Pierre et Jean-3', 'Pierre et Jean-4', 'Pigoule', 'Pirouette-31', 'Pirouette-5', 'Plume-Patte-5', 'Plume-patte-32', 'Pupilles de Neptune de Lille #1-3', 'Pupilles de Neptune de Lille #2-1', 'Pupilles de Neptune de Lille-1', "Qu'Importe", 'Quand-Mme-2', 'Quand-Mme-33', 'Racing Club de France', 'Red Indian', 'Rose Pompon', 'Rowing Club Castillon-3', 'Rozenn-3', 'Sandra', 'Sarcelle-3', 'Sarcelle-35', 'Scamasaxe-2', 'Scamasaxe-3', 'Scamasaxe-34', 'Sidi Fekkar-36', 'Sidi-Fekkar-14', 'Singy-37', 'Singy-7', 'Smyrna', 'Snowten III', 'Societ Nautique de la Marne', 'Societ Nautique de la Marne-1', 'Societ Nautique de la Marne-3', 'Socit Nautique de Bayonne', 'Socit Nautique de Bayonne-1', 'Socit Nautique de Bayonne-2', 'Socit Nautique de la Basse Seine-1', 'Socit Nautique de la Basse Seine-2', 'Souriceau-38', 'Souriceau-4', 'Souvenance', 'Stade Franais AC-2', 'Suzon IV-39', 'Suzon IV-5', 'Tornade-16', 'Tournade-40', 'Tramontane', 'Tritons Lillois-2', 'Turquoise-1', 'Turquoise-3', 'USFSA', 'Union des Socits Franais de Sports Athletiques', 'United States/France', 'Verveine-19', 'Verveine-41', 'Virginie', 'Whitini Star']
  USA (97): ['A North American Team', 'Angelita', 'Angerburg', 'Aphrodite', 'Atalanta Boat Club-1', 'Atalanta Boat Club-2', 'BLO Polo Club, Rugby', 'Babe', 'Bingo', 'Boston Archers', 'Brentina', 'Central Turnverein, Chicago', 'Century Boat Club-1', 'Chicago Archers', 'Chicago Athletic Association', 'Chicago Athletic Association-2', "Christian Brothers' College-1", 'Cincinnati Archers', 'Comanche', 'Complex II', 'Concordia Turnverein, St Louis', 'Davenport Turngemeinde, Davenport', 'Formosa', 'Foxhunters Hurlingham', 'Frieda', 'Frimousse', 'Gallant', 'Germany/United States', 'Glider', 'Hilarius', 'Independent Rowing Club-3', 'Jupiter', 'Kathleen', 'La Salle Turnverein, Chicago', 'Llanoria', 'Margaret', 'Milwaukee Athletic Club-1', 'Milwaukee Turnverein, Milwaukee', 'Minotaur', 'Missouri Athletic Club-3', 'Mound City Rowing Club-2', 'Mystery', 'Mythilus', 'New York Athletic Club', 'New York Athletic Club #1-1', 'New York Athletic Club #2-4', 'New York Athletic Club-1', 'New York Athletic Club-4', 'New York Turnverein, New York', 'Norwegier Turnverein, Brooklyn', 'Passaic Turnverein, Passaic', 'Philadelphia Turngemeinde, Philadelphia', 'Potomac Archers', 'Ravel', 'Ravenswood Boat Club-2', 'Rhythm', 'Rush IV', 'Seawanhaka Boat Club-1', 'Shrew II', 'Skidoo', 'Socialer Turnverein, Detroit', 'South St Louis Turnverein, St Louis', 'Spirit III', 'Spirit VI', 'St. Louis Amateur Athletic Association', 'St. Louis Southwest Turnverein #1-2', 'St. Louis Southwest Turnverein #2-3', 'St. Rose-2', 'Three Star Too', 'Tineke', 'Trans-Mississippi Golf Association-2', 'Turnverein Vorwrts, Chicago', 'Turnverein Vorwrts, Cleveland', 'Union des Socits Franais de Sports Athletiques', 'United States', 'United States Golf Association-3', 'United States-1', 'United States-10', 'United States-11', 'United States-12', 'United States-13', 'United States-14', 'United States-2', 'United States-3', 'United States-4', 'United States-5', 'United States-6', 'United States-7', 'United States-8', 'United States-9', 'United States/France', 'United States/Great Britain', 'Vesper Boat Club', 'Vim III', 'Western Golf Association-1', 'Western Rowing Club-3', 'Widgeon']
  GBR (96): ['Amateur Athletic Association', 'Ancora', 'Andromeda', 'Australia/Great Britain', 'BLO Polo Club, Rugby', 'Bagatelle Polo Club, Paris', 'Beaver', 'Bluebottle', 'Bohemia/Great Britain', 'Bona Fide', 'Brat', 'Brynhild-2', 'Cambridge University Boat Club-2', 'Ceres II', 'Chuckles', 'Cicely-1', 'Cobweb-1', 'Cornwall', 'Devon and Somerset Wanderers', 'Dormy-1', 'Dylan-2', 'Emily', 'England', 'England-1', 'Feo', 'Fortuna', 'Foxhunters Hurlingham', 'France/Great Britain', 'Gem II', 'Great Britain', 'Great Britain-1', 'Great Britain-2', 'Great Britain-3', 'Great Britain-4', 'Great Britain/Germany', 'Gyrinus-1', 'Hera-1', 'Heroine', 'Hurlingham-2', 'Ireland', 'Ireland-2', 'Ireland-3', 'Johan', 'Joy', 'K Division Metropolitan Police Team-3', 'Lady C', 'Lalage', 'Lancet', 'Laurea-1', 'Leander Club #1-1', 'Leander Club #2-2', 'Leander Club-1', 'Leander Club-2', 'Libellule de Paris', 'Liverpool Police Team-2', 'London City Police-1', 'Lucky Star', 'Magdalen College Boat Club-1', 'Mistral Hojris', 'Moseley Wanderers', 'Mouchette-2', 'Nan-2', 'New College, Oxford-2', 'Olle', 'Omilos Ereton Smyrnis', 'Osborne Swimming Club, Manchester', 'Paka', 'Potsdam', 'Quicksilver-2', 'Roehampton-1', 'Sabre', 'Salamander', 'Saskia', 'Scotia', 'Scotland', 'Scotland-2', 'Scotland-3', 'Sea Dog-2', 'Sibindi-2', 'Smyrna', 'Sorais-2', 'Starlight III', 'Swift', 'Thames Rowing Club', 'Titia', 'Twinkle', 'Union des Socits Franais de Sports Athletiques', 'Unique', 'United States/Great Britain', 'Univ. of Brussels', 'Upton Park FC', 'Vision', 'Wales-4', 'Wolseley-Siddeley-1', 'Yeoman VII', 'Yeoman XII']
  SWE (52): ['Ali-Baba II', 'Aloha II', 'Bissbi', 'Briar', 'Chance', 'Denmark/Sweden', 'Elsie', 'Erna Signe', 'Floresco', 'Freja', 'Galejan', 'Gteborgs Roddfrening-2', 'Gteborgs Roddklubb-1', 'Hayama', 'Hojwa', 'Humbug V', 'Ilderim', 'Ingegerd', 'K.S.S.S. 1912-2', 'Kerstin-1', 'Kitty-1', 'Kuling', 'Kullan', 'Lasha', 'Lotta IV', 'Marga-2', 'Mari', 'May Be', 'May Be VII', 'Roddklubben af 1912-1', 'Roddklubben af 1912-2', 'Rush V', 'Rush VII', 'Saga-2', 'Sans Atout-1', 'Sass-2', 'Sif', 'Sjovinge', 'Slaghoken', 'Slaghoken II', 'Solos Carex', 'Sunshine', 'Sweden', 'Sweden-1', 'Sweden-2', 'Sweden-3', 'Sweden-4', 'Swedish Star', 'Sylvia', 'Tornado', 'Vaxholm Roddklubb', 'Vinga-1']
  NOR (46): ['Apache', 'Atlanta', 'Bera', 'Eleda', 'Elisabeth V', 'Elisabeth X', 'Encore', 'Fornebo', 'Fram', 'Fram III', 'Hamburg', 'Heira II', 'Irene', 'Jo', 'KNS', 'Kristiania Roklub', 'Kristiania Roklub-1', 'Lett', 'Lucky', 'Lully II', 'Lyn-2', 'Magda IX', 'Marmi II-1', 'Monica', 'Mosk II', 'Nora', 'Noreg', 'Norna', 'Norway', 'Norway-1', 'Norway-2', 'Norway-3', 'Norwegian Rowing Association', 'Norwegier Turnverein, Brooklyn', 'Ormsund Roklub-2', 'Pan', 'Pan II', 'Sildra-1', 'Silja', 'Sirene', 'Sonja II', 'Stella-2', 'Struten', 'Studenternes Roklub-2', 'Taifun', 'Viking']
  GER (43): ['Aschenbrodel', 'Bellatrix IX', 'Bellatrix XIII', 'Berliner Ruderclub', 'Berliner Ruderclub Sport-Borussia-1', 'Berliner Ruderverein von 1876-2', 'Bonaparte', 'Bronia', 'Deutscher Schwimm Verband Berlin', 'Dinah V', 'Elvis Va', 'Favorite Hammonia-3', 'Frankfurt Club', 'Germania II', 'Germania Ruder Club, Hamburg', 'Germania Ruder Club, Hamburg-2', 'Germany', 'Germany-1', 'Germany-2', 'Germany-3', 'Germany/United States', 'Great Britain/Germany', 'Gustel V', 'Gustel X', 'Gustl XI', 'Ludwigshafener Ruder Verein-1', 'Ludwigshafener Ruderverein', 'Macky VI', 'Mutafo', 'Nirwana', 'Paka V', 'Pan', 'Rostock', 'Satchmo', 'South St Louis Turnverein, St Louis', 'St. Louis Southwest Turnverein #2-3', 'Subbnboana', 'Tantalus', 'Tilly', 'Tom Kyle', 'Turnverein Vorwrts, Chicago', 'Wannsee', 'Wendehals']
  ITA (35): ['Aldebaran', 'Aldebaran II', 'Aretusa', 'Argeste', 'Augsburg', 'Ausonia', 'Bamba', 'Barion/Bari-2', 'Bucintoro Venezia', 'Bucintoro Venezia-1', 'Ciocca', 'Ciocca II', 'Enotria', 'Esperia', 'Galatea II', 'Grifone', 'Italia', 'Italy', 'Italy-1', 'Italy-2', 'Legionario', 'Marinai della nave da guerra "Varese"', 'Mebi', 'Merope', 'Merope III', 'Mirtala', 'Pegaso', 'Pistoja/Firenze', 'Roma', 'Romolo', 'Twins II', 'Twins VIII', 'Umberta V', 'Venilia', 'Voloira II']
  CAN (31): ['Argo II', 'Argonaut Rowing Club', 'Ariel', 'Beaver', 'Canada', 'Canada-1', 'Canada-2', 'Caprice', 'Dresden', 'Galt Football Club', 'Glisten', 'Gran Gesto', 'Jet', 'Mad Dog', 'Manana', 'Mohawk Indians-2', 'Orion', 'Pop Art', 'SagaII', 'Santa Maria', 'Scaup', 'Scram', 'Serendipity', 'State VI', 'Syndi', 'Tomahawk II', 'Toronto Argonauts', 'Trickson VI', 'Whirlaway', 'Windor', 'Winnipeg Shamrocks-1']
  GRE (29): ['Athens-2', 'Ethnikos Gymnastikos Syllogos', 'Greece', 'Greece-1', 'Greece-2', 'Greece-3', 'Greece-4', 'Large boat, Central Naval Prep School "Poros"-1', 'Lemzos Thorichton "Psara"-3', 'Lemzos Thorichton "Spetsai"-4', 'Life boat naval ship "Spetsai"-1', 'Marie-Tim', 'Nautikos Omilos-3', 'Nephos I', 'Nikh', 'Nirefs', 'Olympion', 'Omas Helliniki P. S.', 'Omilos Ereton Peiraios-2', 'Omilos Ereton Smyrnis', 'Pan-Hellenic Athletic Club', 'Panhellenios Gymnastikos Syllogos-1', 'Peiraikos Syndesmos-2', 'Phalainis ton Thorichtou "Hydra"-2', 'Phalainis ton Thorichtou "Psara"-3', 'Proteus II', 'Royal Club Nautique de Gand', 'Thessalonki-1', 'Zefyros']
  DEN (29): ['Anitra', 'Bonzo', 'Chok', 'Clearwater', 'Dansk Idrts Forbund', 'Denmark', 'Denmark-1', 'Denmark-2', 'Denmark-3', 'Denmark-4', 'Denmark/Sweden', 'Digby', 'Don Schufro', 'Hi-Hi', 'Jill', 'Kiel', 'Miss Denmark 1964', 'Morena', 'Nurdug II', 'Nykjbings paa Falster', 'Polyteknisk Roklub-1', 'Roklubb Kbnhavn-2', 'Skum', 'Snap', 'Snude', 'Tip', 'Web II', 'Web III', 'White Lady']
  NED (27): ['Amstel Amsterdam', 'Barco Deloro', 'Beatrijs III-1', 'Bem II', 'Boreas-2', 'Daisy', 'DeRuyter', 'Holland', 'Hollandia', 'Joy', 'Kemphaan', 'Mascotte', 'Minerva Amsterdam', 'Nadine', 'Netherlands', 'Netherlands-1', 'Netherlands-2', 'Nrnberg', 'Oranje', 'Salinero', 'St. Margrite', 'Starita', 'Sunrise', 'Thalatta', 'Trintel II', 'Univ. of Brussels', 'Willem-Six']
  FIN (24): ['Bella', 'Bremen', 'Chaje II', 'Finland', 'Finland-1', 'Finland-2', 'Finn II', 'Heatherbell', 'Helsingfors R. K.', 'Inga-Lill XXXXIII', 'Lucky Girl-1', 'Lucky Star', 'Lynn', 'Nina', 'Raili', 'Ralia', 'Rififi', 'Sheerio', 'Squid III', 'Teresita', 'Tu-Fri', 'Vinha', 'Xantippa', 'rn-2']
  AUS (23): ['Amateur Athletic Association', 'Australia', 'Australia-1', 'Australia-2', 'Australia-3', 'Australia/Great Britain', 'Barrenjoey', 'Buraddoo', 'Cambria', 'Diablo', 'Falcon IV', 'Falcon VI', 'Gabbiano', 'Greenoaks Dundee', 'Hornet', 'Maryke', 'Moorina', 'Naiad', 'Pakaria', 'Paula', 'Quando Quando', 'Relampago', 'Vinha']
  BEL (22): ['Antwerpia V', 'Belgium', 'Belgium-1', 'Belgium-2', 'Belgium-3', 'Belgium-4', 'Brussels Swimming and Water Polo Club', 'Ciss', 'Danzig', 'Dolfijn', 'Edelweiss II-1', 'Freddy', 'Girl Pat', 'Lalage', 'Meteor', 'Pupilles de Neptune de Lille #1-3', 'Royal Club Nautique de Gand', 'Suzy-2', 'Tan-Fe-Pah', 'Ubu', 'Univ. of Brussels', 'Zut']
  POR (20): ['Alcaid', 'Argus', 'Calcinhas', 'Camelia', 'Canopus', 'Ciocca III', 'Espadarte', 'Espardate', 'Faneca', 'Galopin De La Font', 'Grifo III', 'Grifo IV', 'Hannover', "Ma'Lindo", 'Notavel', 'Oxalis', 'Portugal', 'Sjhxa', 'Symphony', 'Vicking']
  ARG (18): ['Acturus', 'Antares', 'Arcturus', 'Ardilla', 'Argentina', 'Argentina-1', 'Argentina-2', 'Blue Red', 'Covunco III', 'Cupidon III', 'Djinn', 'Gullvinge', 'Matrero II', 'Mizar', 'Pampero', 'Rampage', 'Tango', 'Wiking']
  SUI (18): ['Alain IV', 'Ali-Baba II', 'Ali-Baba IV', 'Ali-Baba IX', 'Ali-Baba VI', 'Baccara', 'Ballerina IV', 'Fantasio III', 'Kln', 'Lerina', 'Pousse-Moi Pas VII', 'Switzerland', 'Switzerland-1', 'Switzerland-2', 'Tim-Tam III', 'Ylliam II', 'Ylliam VII', 'Ylliam VIII']
  JPN (15): ['Boreas', 'Danaldo', 'Dow Jones', 'Essen', 'Japan', 'Japan-1', 'Japan-2', 'Japan-3', 'Miss Nippon V', 'MitaII', 'Myojo', 'Rambo', 'Riccar', 'Roy', 'Whisper']
  URS (15): ['Almaz', 'Burevestnik', 'Druzhba', 'Kon-Tiki', 'Korshun', 'Neptun II', 'Nokaut II', 'Olen', 'Persey', 'Soviet Union', 'Taifun', 'Tornado', 'Tulilind', 'Uragan', 'Viktoriya']
  BRA (13): ['Andorinha', 'Brazil', 'Brazil-1', 'Brazil-2', 'Bu III', 'Buscape II', 'Clementine V', 'Escapade', 'Inca', 'Lbeck', 'Pimm', 'Terrible', 'Vento Sul']

In [18]:
# Show ALL NOCs with >1 spelling - full list for the unification table
print('=== ALL NOCs with multiple Team spellings ===')
for _, row in multi_name.iterrows():
    print(f'{row["NOC"]}: {row["Team"]}')

=== ALL NOCs with multiple Team spellings ===
FRA: ['Alcyon-6', 'Alcyon-7', 'Allegro', 'Aloha II', 'Amulet-3', 'Amulet-7', 'Ariette-10', 'Ariette-8', 'Astrid III', 'BLO Polo Club, Rugby', 'Baby-1', 'Baby-9', 'Bagatelle Polo Club, Paris', 'C.V.A.-14', 'C.V.A.-7', 'Calimucho', 'Calypse II', 'Camille', 'Carabinier-15', 'Carabinier-5', 'Cercle Nautique de Reims-4', "Cercle de l'Aviron Roubaix-4", 'Chicago Athletic Association', 'Cinara-13', 'Club Nautique de Dieppe-5', 'Club Nautique de Franais-1', 'Club Nautique de Lyon-2', 'Colette-10', 'Colette-12', 'Compigne Polo Club', 'Crabe I-11', 'Crabe I-2', 'Crabe I-3', 'Crabe II-1', 'Crabe II-12', 'Crabe II-4', 'Crocodile-11', 'Crocodile-13', 'Cupidon Viking', 'Damoiselle', 'Demi-Mondaine-15', 'Demi-Mondaine-17', 'Diabolo St Maurice', 'Dick-8', 'Ducky-16', 'Ducky-4', 'EA II', 'Eissero VI', 'Esterel-1', 'Fada', 'Fantlet-2', 'Fantlet-7', 'Favorite-1', 'Favorite-17', 'Femur-1', 'Femur-18', 'France', 'France-1', 'France-2', 'France-3', 'France-4', 'France/Great Britain', 'Freia-19', 'Freia-5', 'Frip IV', 'Galopin-20', 'Galopin-9', 'Gam II', 'Gilliatt V', 'Giselle-6', 'Gitana-2', 'Gitana-21', 'Guyoni', 'Gwendoline-2', 'Gwendoline-22', 'Gyp-23', 'Gyp-6', 'Hb-20', 'Hb-24', 'Jeanette-25', 'Jeannette-18', 'Kannibaltje', "L'Aile VI", 'LaBandera', 'Leipzig', 'Libellule de Paris', 'Libellule de Paris-3', 'Mac Miche', 'Mamie-4', 'Mamie-6', 'Marsouin-26', 'Marsouin-8', 'Martha-1', 'Martha-27', 'Mascaret-28', 'Mascaret-4', 'Mignon-29', 'Mignon-3', 'Namoussa', 'Nina Claire-2', 'Nina Claire-30', 'Olle', 'Pettit-Poucet-6', 'Pierre et Jean-3', 'Pierre et Jean-4', 'Pigoule', 'Pirouette-31', 'Pirouette-5', 'Plume-Patte-5', 'Plume-patte-32', 'Pupilles de Neptune de Lille #1-3', 'Pupilles de Neptune de Lille #2-1', 'Pupilles de Neptune de Lille-1', "Qu'Importe", 'Quand-Mme-2', 'Quand-Mme-33', 'Racing Club de France', 'Red Indian', 'Rose Pompon', 'Rowing Club Castillon-3', 'Rozenn-3', 'Sandra', 'Sarcelle-3', 'Sarcelle-35', 'Scamasaxe-2', 'Scamasaxe-3', 'Scamasaxe-34', 'Sidi Fekkar-36', 'Sidi-Fekkar-14', 'Singy-37', 'Singy-7', 'Smyrna', 'Snowten III', 'Societ Nautique de la Marne', 'Societ Nautique de la Marne-1', 'Societ Nautique de la Marne-3', 'Socit Nautique de Bayonne', 'Socit Nautique de Bayonne-1', 'Socit Nautique de Bayonne-2', 'Socit Nautique de la Basse Seine-1', 'Socit Nautique de la Basse Seine-2', 'Souriceau-38', 'Souriceau-4', 'Souvenance', 'Stade Franais AC-2', 'Suzon IV-39', 'Suzon IV-5', 'Tornade-16', 'Tournade-40', 'Tramontane', 'Tritons Lillois-2', 'Turquoise-1', 'Turquoise-3', 'USFSA', 'Union des Socits Franais de Sports Athletiques', 'United States/France', 'Verveine-19', 'Verveine-41', 'Virginie', 'Whitini Star']
USA: ['A North American Team', 'Angelita', 'Angerburg', 'Aphrodite', 'Atalanta Boat Club-1', 'Atalanta Boat Club-2', 'BLO Polo Club, Rugby', 'Babe', 'Bingo', 'Boston Archers', 'Brentina', 'Central Turnverein, Chicago', 'Century Boat Club-1', 'Chicago Archers', 'Chicago Athletic Association', 'Chicago Athletic Association-2', "Christian Brothers' College-1", 'Cincinnati Archers', 'Comanche', 'Complex II', 'Concordia Turnverein, St Louis', 'Davenport Turngemeinde, Davenport', 'Formosa', 'Foxhunters Hurlingham', 'Frieda', 'Frimousse', 'Gallant', 'Germany/United States', 'Glider', 'Hilarius', 'Independent Rowing Club-3', 'Jupiter', 'Kathleen', 'La Salle Turnverein, Chicago', 'Llanoria', 'Margaret', 'Milwaukee Athletic Club-1', 'Milwaukee Turnverein, Milwaukee', 'Minotaur', 'Missouri Athletic Club-3', 'Mound City Rowing Club-2', 'Mystery', 'Mythilus', 'New York Athletic Club', 'New York Athletic Club #1-1', 'New York Athletic Club #2-4', 'New York Athletic Club-1', 'New York Athletic Club-4', 'New York Turnverein, New York', 'Norwegier Turnverein, Brooklyn', 'Passaic Turnverein, Passaic', 'Philadelphia Turngemeinde, Philadelphia', 'Potomac Archers', 'Ravel', 'Ravenswood Boat Club-2', 'Rhythm', 'Rush IV', 'Seawanhaka Boat Club-1', 'Shrew II', 'Skidoo', 'Socialer Turnverein, Detroit', 'South St Louis Turnverein, St Louis', 'Spirit III', 'Spirit VI', 'St. Louis Amateur Athletic Association', 'St. Louis Southwest Turnverein #1-2', 'St. Louis Southwest Turnverein #2-3', 'St. Rose-2', 'Three Star Too', 'Tineke', 'Trans-Mississippi Golf Association-2', 'Turnverein Vorwrts, Chicago', 'Turnverein Vorwrts, Cleveland', 'Union des Socits Franais de Sports Athletiques', 'United States', 'United States Golf Association-3', 'United States-1', 'United States-10', 'United States-11', 'United States-12', 'United States-13', 'United States-14', 'United States-2', 'United States-3', 'United States-4', 'United States-5', 'United States-6', 'United States-7', 'United States-8', 'United States-9', 'United States/France', 'United States/Great Britain', 'Vesper Boat Club', 'Vim III', 'Western Golf Association-1', 'Western Rowing Club-3', 'Widgeon']
GBR: ['Amateur Athletic Association', 'Ancora', 'Andromeda', 'Australia/Great Britain', 'BLO Polo Club, Rugby', 'Bagatelle Polo Club, Paris', 'Beaver', 'Bluebottle', 'Bohemia/Great Britain', 'Bona Fide', 'Brat', 'Brynhild-2', 'Cambridge University Boat Club-2', 'Ceres II', 'Chuckles', 'Cicely-1', 'Cobweb-1', 'Cornwall', 'Devon and Somerset Wanderers', 'Dormy-1', 'Dylan-2', 'Emily', 'England', 'England-1', 'Feo', 'Fortuna', 'Foxhunters Hurlingham', 'France/Great Britain', 'Gem II', 'Great Britain', 'Great Britain-1', 'Great Britain-2', 'Great Britain-3', 'Great Britain-4', 'Great Britain/Germany', 'Gyrinus-1', 'Hera-1', 'Heroine', 'Hurlingham-2', 'Ireland', 'Ireland-2', 'Ireland-3', 'Johan', 'Joy', 'K Division Metropolitan Police Team-3', 'Lady C', 'Lalage', 'Lancet', 'Laurea-1', 'Leander Club #1-1', 'Leander Club #2-2', 'Leander Club-1', 'Leander Club-2', 'Libellule de Paris', 'Liverpool Police Team-2', 'London City Police-1', 'Lucky Star', 'Magdalen College Boat Club-1', 'Mistral Hojris', 'Moseley Wanderers', 'Mouchette-2', 'Nan-2', 'New College, Oxford-2', 'Olle', 'Omilos Ereton Smyrnis', 'Osborne Swimming Club, Manchester', 'Paka', 'Potsdam', 'Quicksilver-2', 'Roehampton-1', 'Sabre', 'Salamander', 'Saskia', 'Scotia', 'Scotland', 'Scotland-2', 'Scotland-3', 'Sea Dog-2', 'Sibindi-2', 'Smyrna', 'Sorais-2', 'Starlight III', 'Swift', 'Thames Rowing Club', 'Titia', 'Twinkle', 'Union des Socits Franais de Sports Athletiques', 'Unique', 'United States/Great Britain', 'Univ. of Brussels', 'Upton Park FC', 'Vision', 'Wales-4', 'Wolseley-Siddeley-1', 'Yeoman VII', 'Yeoman XII']
SWE: ['Ali-Baba II', 'Aloha II', 'Bissbi', 'Briar', 'Chance', 'Denmark/Sweden', 'Elsie', 'Erna Signe', 'Floresco', 'Freja', 'Galejan', 'Gteborgs Roddfrening-2', 'Gteborgs Roddklubb-1', 'Hayama', 'Hojwa', 'Humbug V', 'Ilderim', 'Ingegerd', 'K.S.S.S. 1912-2', 'Kerstin-1', 'Kitty-1', 'Kuling', 'Kullan', 'Lasha', 'Lotta IV', 'Marga-2', 'Mari', 'May Be', 'May Be VII', 'Roddklubben af 1912-1', 'Roddklubben af 1912-2', 'Rush V', 'Rush VII', 'Saga-2', 'Sans Atout-1', 'Sass-2', 'Sif', 'Sjovinge', 'Slaghoken', 'Slaghoken II', 'Solos Carex', 'Sunshine', 'Sweden', 'Sweden-1', 'Sweden-2', 'Sweden-3', 'Sweden-4', 'Swedish Star', 'Sylvia', 'Tornado', 'Vaxholm Roddklubb', 'Vinga-1']
NOR: ['Apache', 'Atlanta', 'Bera', 'Eleda', 'Elisabeth V', 'Elisabeth X', 'Encore', 'Fornebo', 'Fram', 'Fram III', 'Hamburg', 'Heira II', 'Irene', 'Jo', 'KNS', 'Kristiania Roklub', 'Kristiania Roklub-1', 'Lett', 'Lucky', 'Lully II', 'Lyn-2', 'Magda IX', 'Marmi II-1', 'Monica', 'Mosk II', 'Nora', 'Noreg', 'Norna', 'Norway', 'Norway-1', 'Norway-2', 'Norway-3', 'Norwegian Rowing Association', 'Norwegier Turnverein, Brooklyn', 'Ormsund Roklub-2', 'Pan', 'Pan II', 'Sildra-1', 'Silja', 'Sirene', 'Sonja II', 'Stella-2', 'Struten', 'Studenternes Roklub-2', 'Taifun', 'Viking']
GER: ['Aschenbrodel', 'Bellatrix IX', 'Bellatrix XIII', 'Berliner Ruderclub', 'Berliner Ruderclub Sport-Borussia-1', 'Berliner Ruderverein von 1876-2', 'Bonaparte', 'Bronia', 'Deutscher Schwimm Verband Berlin', 'Dinah V', 'Elvis Va', 'Favorite Hammonia-3', 'Frankfurt Club', 'Germania II', 'Germania Ruder Club, Hamburg', 'Germania Ruder Club, Hamburg-2', 'Germany', 'Germany-1', 'Germany-2', 'Germany-3', 'Germany/United States', 'Great Britain/Germany', 'Gustel V', 'Gustel X', 'Gustl XI', 'Ludwigshafener Ruder Verein-1', 'Ludwigshafener Ruderverein', 'Macky VI', 'Mutafo', 'Nirwana', 'Paka V', 'Pan', 'Rostock', 'Satchmo', 'South St Louis Turnverein, St Louis', 'St. Louis Southwest Turnverein #2-3', 'Subbnboana', 'Tantalus', 'Tilly', 'Tom Kyle', 'Turnverein Vorwrts, Chicago', 'Wannsee', 'Wendehals']
ITA: ['Aldebaran', 'Aldebaran II', 'Aretusa', 'Argeste', 'Augsburg', 'Ausonia', 'Bamba', 'Barion/Bari-2', 'Bucintoro Venezia', 'Bucintoro Venezia-1', 'Ciocca', 'Ciocca II', 'Enotria', 'Esperia', 'Galatea II', 'Grifone', 'Italia', 'Italy', 'Italy-1', 'Italy-2', 'Legionario', 'Marinai della nave da guerra "Varese"', 'Mebi', 'Merope', 'Merope III', 'Mirtala', 'Pegaso', 'Pistoja/Firenze', 'Roma', 'Romolo', 'Twins II', 'Twins VIII', 'Umberta V', 'Venilia', 'Voloira II']
CAN: ['Argo II', 'Argonaut Rowing Club', 'Ariel', 'Beaver', 'Canada', 'Canada-1', 'Canada-2', 'Caprice', 'Dresden', 'Galt Football Club', 'Glisten', 'Gran Gesto', 'Jet', 'Mad Dog', 'Manana', 'Mohawk Indians-2', 'Orion', 'Pop Art', 'SagaII', 'Santa Maria', 'Scaup', 'Scram', 'Serendipity', 'State VI', 'Syndi', 'Tomahawk II', 'Toronto Argonauts', 'Trickson VI', 'Whirlaway', 'Windor', 'Winnipeg Shamrocks-1']
GRE: ['Athens-2', 'Ethnikos Gymnastikos Syllogos', 'Greece', 'Greece-1', 'Greece-2', 'Greece-3', 'Greece-4', 'Large boat, Central Naval Prep School "Poros"-1', 'Lemzos Thorichton "Psara"-3', 'Lemzos Thorichton "Spetsai"-4', 'Life boat naval ship "Spetsai"-1', 'Marie-Tim', 'Nautikos Omilos-3', 'Nephos I', 'Nikh', 'Nirefs', 'Olympion', 'Omas Helliniki P. S.', 'Omilos Ereton Peiraios-2', 'Omilos Ereton Smyrnis', 'Pan-Hellenic Athletic Club', 'Panhellenios Gymnastikos Syllogos-1', 'Peiraikos Syndesmos-2', 'Phalainis ton Thorichtou "Hydra"-2', 'Phalainis ton Thorichtou "Psara"-3', 'Proteus II', 'Royal Club Nautique de Gand', 'Thessalonki-1', 'Zefyros']
DEN: ['Anitra', 'Bonzo', 'Chok', 'Clearwater', 'Dansk Idrts Forbund', 'Denmark', 'Denmark-1', 'Denmark-2', 'Denmark-3', 'Denmark-4', 'Denmark/Sweden', 'Digby', 'Don Schufro', 'Hi-Hi', 'Jill', 'Kiel', 'Miss Denmark 1964', 'Morena', 'Nurdug II', 'Nykjbings paa Falster', 'Polyteknisk Roklub-1', 'Roklubb Kbnhavn-2', 'Skum', 'Snap', 'Snude', 'Tip', 'Web II', 'Web III', 'White Lady']
NED: ['Amstel Amsterdam', 'Barco Deloro', 'Beatrijs III-1', 'Bem II', 'Boreas-2', 'Daisy', 'DeRuyter', 'Holland', 'Hollandia', 'Joy', 'Kemphaan', 'Mascotte', 'Minerva Amsterdam', 'Nadine', 'Netherlands', 'Netherlands-1', 'Netherlands-2', 'Nrnberg', 'Oranje', 'Salinero', 'St. Margrite', 'Starita', 'Sunrise', 'Thalatta', 'Trintel II', 'Univ. of Brussels', 'Willem-Six']
FIN: ['Bella', 'Bremen', 'Chaje II', 'Finland', 'Finland-1', 'Finland-2', 'Finn II', 'Heatherbell', 'Helsingfors R. K.', 'Inga-Lill XXXXIII', 'Lucky Girl-1', 'Lucky Star', 'Lynn', 'Nina', 'Raili', 'Ralia', 'Rififi', 'Sheerio', 'Squid III', 'Teresita', 'Tu-Fri', 'Vinha', 'Xantippa', 'rn-2']
AUS: ['Amateur Athletic Association', 'Australia', 'Australia-1', 'Australia-2', 'Australia-3', 'Australia/Great Britain', 'Barrenjoey', 'Buraddoo', 'Cambria', 'Diablo', 'Falcon IV', 'Falcon VI', 'Gabbiano', 'Greenoaks Dundee', 'Hornet', 'Maryke', 'Moorina', 'Naiad', 'Pakaria', 'Paula', 'Quando Quando', 'Relampago', 'Vinha']
BEL: ['Antwerpia V', 'Belgium', 'Belgium-1', 'Belgium-2', 'Belgium-3', 'Belgium-4', 'Brussels Swimming and Water Polo Club', 'Ciss', 'Danzig', 'Dolfijn', 'Edelweiss II-1', 'Freddy', 'Girl Pat', 'Lalage', 'Meteor', 'Pupilles de Neptune de Lille #1-3', 'Royal Club Nautique de Gand', 'Suzy-2', 'Tan-Fe-Pah', 'Ubu', 'Univ. of Brussels', 'Zut']
POR: ['Alcaid', 'Argus', 'Calcinhas', 'Camelia', 'Canopus', 'Ciocca III', 'Espadarte', 'Espardate', 'Faneca', 'Galopin De La Font', 'Grifo III', 'Grifo IV', 'Hannover', "Ma'Lindo", 'Notavel', 'Oxalis', 'Portugal', 'Sjhxa', 'Symphony', 'Vicking']
ARG: ['Acturus', 'Antares', 'Arcturus', 'Ardilla', 'Argentina', 'Argentina-1', 'Argentina-2', 'Blue Red', 'Covunco III', 'Cupidon III', 'Djinn', 'Gullvinge', 'Matrero II', 'Mizar', 'Pampero', 'Rampage', 'Tango', 'Wiking']
SUI: ['Alain IV', 'Ali-Baba II', 'Ali-Baba IV', 'Ali-Baba IX', 'Ali-Baba VI', 'Baccara', 'Ballerina IV', 'Fantasio III', 'Kln', 'Lerina', 'Pousse-Moi Pas VII', 'Switzerland', 'Switzerland-1', 'Switzerland-2', 'Tim-Tam III', 'Ylliam II', 'Ylliam VII', 'Ylliam VIII']
JPN: ['Boreas', 'Danaldo', 'Dow Jones', 'Essen', 'Japan', 'Japan-1', 'Japan-2', 'Japan-3', 'Miss Nippon V', 'MitaII', 'Myojo', 'Rambo', 'Riccar', 'Roy', 'Whisper']
URS: ['Almaz', 'Burevestnik', 'Druzhba', 'Kon-Tiki', 'Korshun', 'Neptun II', 'Nokaut II', 'Olen', 'Persey', 'Soviet Union', 'Taifun', 'Tornado', 'Tulilind', 'Uragan', 'Viktoriya']
BRA: ['Andorinha', 'Brazil', 'Brazil-1', 'Brazil-2', 'Bu III', 'Buscape II', 'Clementine V', 'Escapade', 'Inca', 'Lbeck', 'Pimm', 'Terrible', 'Vento Sul']
AUT: ['30. Februar', 'Austria', 'Austria-1', 'Austria-2', 'Breslau', 'Brigantia', 'Donar III', 'Evita VI', 'May-Be 1960', 'Philadelphia Turngemeinde, Philadelphia', 'R.-V. Germania, Leitmeritz', 'Surprise']
ESP: ['Amolgavar', 'Canopus', 'Fruits', 'Galerna', 'Pasodoble', 'Posillipo III', 'Ral-Club Barcelona', 'Spain', 'Spain-1', 'Spain-2', 'Tajamar']
HUN: ['Balaton', 'Hungaria', 'Hungaria Evezos Egylet', 'Hungary', 'Hungary-1', 'Hungary-2', 'Hungary-3', 'Knigsberg', 'Olimpia', 'Pannonia RC/National RC']
BAH: ['Bahamas', 'Bim', 'Combine', 'Gem', 'Gem III', 'Gem IV', 'Gem VII', 'Guanahani', 'John B', 'Yeoman']
RSA: ['Boer Team', 'Hakahana', 'Impala', 'Shoveller', 'South Africa', 'South Africa-1', 'South Africa-2', 'Springbok', 'Yeoman V']
IRL: ['Akatonbo', 'Aletta', 'Ireland', 'Ireland-1', 'Ireland-2', 'The Cloud', 'Three Leaves']
MEX: ['A North American Team', 'Acipactli', 'Chamukina', 'Mexico', 'Nausikaa 4', 'Tlaloc', 'Xolotl']
CUB: ['Cuba', 'Cuba-1', 'Cuba-2', 'Hatuey', 'Kurush II', 'Kurush IV', 'Vesania']
NZL: ['Harmony', 'Jest', 'New Zealand', 'Osborne Swimming Club, Manchester', 'Pandora', 'Red Dragon']
BER: ['Bermuda', 'Bermudes', 'Bermudian', 'Oleander II', 'Oleander XII', 'Pam']
YUG: ['Cha-Cha III', 'Konstanz', 'Primorka', 'Yugoslavia', 'Yugoslavia-1', 'Yugoslavia-2']
RUS: ['Bylina-2', 'Gallia II', 'Norman-1', 'Russia', 'Russia-1', 'Russia-2']
THA: ['Linglom', 'Siames-Cat', 'Thailand', 'Thailand-1', 'Thailand-2', 'Tichiboo']
INA: ['Indonesia', 'Indonesia-1', 'Indonesia-2', 'Partenope', 'Tengiri']
BOH: ['Bohemia', 'Bohemia-1', 'Bohemia-2', 'Bohemia-3', 'Bohemia/Great Britain']
SGP: ['June Climene', 'Rika II', 'Singapore', 'Singapore-1', 'Singapore-2']
POL: ['Danuta', 'Poland', 'Poland-1', 'Poland-2', 'Poland-3']
HKG: ['Hong Kong', 'Hong Kong, China', 'Hong Kong-1', 'Hong Kong-2', 'Phoenix']
PRK: ['DPR Korea', 'North Korea', 'North Korea-1', 'North Korea-2']
GDR: ['East Germany', 'East Germany-1', 'East Germany-2', 'East Germany-3']
CHN: ['China', 'China-1', 'China-2', 'China-3']
FRG: ['West Germany', 'West Germany-1', 'West Germany-2', 'West Germany-3']
CZE: ['Czech Republic', 'Czech Republic-1', 'Czech Republic-2', 'Czechia']
TUR: ['Cuxhaven', 'Marmara', 'Turkey', 'Türkiye']
URU: ['Bajazzo', 'Heidelberg', 'Nortazo', 'Uruguay']
KOR: ['Korea', 'South Korea', 'South Korea-1', 'South Korea-2']
TCH: ['Czechoslovakia', 'Czechoslovakia-1', 'Czechoslovakia-2', 'Czechoslovakia-3']
ROU: ['Romania', 'Romania-1', 'Romania-2']
TPE: ['Chinese Taipei', 'Chinese Taipei-1', 'Chinese Taipei-2']
UKR: ['Ukraine', 'Ukraine-1', 'Ukraine-2']
CGO: ['Congo', 'Congo (Brazzaville)', 'Republic of the Congo']
EST: ['Brandenburg', 'Estonia', 'Tutti V']
CIV: ["Cote d'Ivoire", "Côte d'Ivoire", 'Ivory Coast']
BLR: ['Belarus', 'Belarus-1', 'Belarus-2']
BUL: ['Bulgaria', 'Bulgaria-1', 'Bulgaria-2']
EUN: ['Unified Team', 'Unified Team-1', 'Unified Team-2']
STP: ['Sao Tome & Principe', 'Sao Tome and Principe', 'São Tomé and Príncipe']
SRB: ['Serbia', 'Serbia-1', 'Serbia-2']
SLO: ['Slovenia', 'Slovenia-1', 'Slovenia-2']
TLS: ['East Timor', 'Timor Leste', 'Timor-Leste']
SVK: ['Slovakia', 'Slovakia-1', 'Slovakia-2']
MYA: ['Kingfisher', 'Myanmar', 'Yangon']
MAS: ['Malaysia', 'Malaysia-1', 'Malaysia-2']
LAT: ['Latvia', 'Latvia-1', 'Latvia-2']
MON: ['Damoiselle IV', 'Hirondelle', 'Monaco']
COD: ['Congo (Kinshasa)', 'DR Congo', 'Democratic Republic of the Congo']
NGR: ['Nigeria', 'Nigeria-1', 'Nigeria-2']
ISV: ['United States Virgin Islands', 'Virgin Islands', 'Virgin Islands, US']
IND: ['India', 'India-1', 'India-2']
MRI: ['Mauritius', 'Mauritius-1', 'Mauritius-2']
PHI: ['Kalayaan', 'Patricia', 'Philippines']
FSM: ['Federated States of Micronesia', 'Micronesia']
EOR: ['EOR', 'Refugee Olympic Team']
GBS: ['Guinea Bissau', 'Guinea-Bissau']
GAM: ['Gambia', 'The Gambia']
CAF: ['Centr Afric Re', 'Central African Republic']
CHI: ['Chile', 'Mainz']
BRU: ['Brunei', 'Brunei Darussalam']
CAM: ['Cambodia', 'GyoshuII']
BIH: ['Bosnia & Herzegovina', 'Bosnia and Herzegovina']
ANZ: ['Australasia', 'Sydney Rowing Club']
COL: ['Colombia', 'Racing Club de France']
CPV: ['Cabo Verde', 'Cape Verde']
HAI: ['Haiti', 'Union des Socits Franais de Sports Athletiques']
IVB: ['British Virgin Islands', 'Virgin Islands, B']
LIB: ['Lebanon', 'Maid of Lebanon']
MDA: ['Moldova', 'Republic of Moldova']
MKD: ['Macedonia', 'North Macedonia']
LAO: ['Lao PDR', 'Laos']
MLT: ['Malta', 'Merope']
IRI: ['IR Iran', 'Iran']
JAM: ['Jamaica', 'Miss Nippon IV']
RHO: ['Peri', 'Rhodesia']
SWZ: ['Eswatini', 'Swaziland']
SKN: ['Saint Kitts and Nevis', 'St Kitts and Nevis']
UAE: ['UA Emirates', 'United Arab Emirates']
TTO: ['Firebird II', 'Trinidad and Tobago']
VEN: ['Espuma del Mar', 'Venezuela']
VIN: ['Saint Vincent and the Grenadines', 'StVincent&Grenadines']
WIF: ['Circus', 'West Indies Federation']
ZIM: ['Peri II', 'Zimbabwe']

## 7. Multi-Team Detection (Dash-Suffix Pattern)

**Why**: Team names like "United States-1" or "Germany-2" indicate a country sent multiple teams in the same event. PIPELINE.md Step 1.1.2 says to preserve this as `is_multi_team`. We need to know how common this pattern is and which countries use it.

In [19]:
import re

# Find all Team names matching "-<number>" pattern
dash_suffix = df['Team'].str.extract(r'^(.*)-(\d+)$')
dash_mask = dash_suffix[1].notna()

print(f'Rows with dash-suffix (e.g. "Team-1"): {dash_mask.sum():,} ({dash_mask.sum()/len(df)*100:.2f}%)')
print(f'Unique Team names with dash-suffix: {df.loc[dash_mask, "Team"].nunique()}')
print()

# Which base countries have multi-team entries
multi_team_bases = dash_suffix.loc[dash_mask, 0].unique()
print(f'Unique base country names with multi-team: {len(multi_team_bases)}')
print()
print('Examples:')
display(df.loc[dash_mask, ['Team', 'NOC', 'Year', 'Event']].drop_duplicates().head(20))

Rows with dash-suffix (e.g. "Team-1"): 2,795 (1.11%)
Unique Team names with dash-suffix: 354

Unique base country names with multi-team: 217

Examples:

             Team  NOC  Year                                      Event
1770  Argentina-2  ARG  2000    Beach Volleyball Men's Beach Volleyball
2013  Argentina-1  ARG  2008                       Tennis Men's Doubles
2043  Argentina-2  ARG  2008                       Tennis Men's Doubles
2121  Argentina-2  ARG  1924                       Tennis Men's Doubles
2175  Argentina-2  ARG  2004                       Tennis Men's Doubles
2206  Argentina-1  ARG  2000    Beach Volleyball Men's Beach Volleyball
2358  Argentina-1  ARG  2016                       Tennis Men's Doubles
2369  Argentina-2  ARG  2016                       Tennis Men's Doubles
2443  Argentina-1  ARG  1924                       Tennis Men's Doubles
2486  Argentina-1  ARG  2004                       Tennis Men's Doubles
5327  Australia-2  AUS  2016  Beach Volleyball Women's Beach Volleyball
5415  Australia-1  AUS  2000                    Badminton Mixed Doubles
5451  Australia-2  AUS  2012  Beach Volleyball Women's Beach Volleyball
5504  Australia-1  AUS  2012  Beach Volleyball Women's Beach Volleyball
5505  Australia-1  AUS  2016  Beach Volleyball Women's Beach Volleyball
5963  Australia-2  AUS  2004                 Table Tennis Men's Doubles
6151  Australia-2  AUS  1996                    Badminton Mixed Doubles
6228  Australia-2  AUS  2000                  Badminton Women's Doubles
6348  Australia-2  AUS  2000                 Table Tennis Men's Doubles
6429  Australia-1  AUS  1996  Beach Volleyball Women's Beach Volleyball

## 8. Garbled / Non-ASCII Team Names

**Why**: PIPELINE.md Section 1.0 mentions "garbled code" handling from the previous attempt. Non-ASCII characters in Team names may indicate encoding issues, Chinese characters, or special symbols (accented letters like e, u, etc. are fine — these are real names). We distinguish: (a) valid accented Latin scripts vs (b) encoding artifacts.

In [20]:
def char_analysis(s):
    """Classify a string by its character composition."""
    if pd.isna(s):
        return 'NaN'
    if '\ufffd' in s or '\x00' in s:
        return 'GARBLED'
    if all(ord(c) < 128 for c in s):
        return 'ASCII'
    return 'NON_ASCII'

df['team_char_type'] = df['Team'].apply(char_analysis)
print('Team name character type distribution:')
print(df['team_char_type'].value_counts())
print()

non_ascii = df[df['team_char_type'] == 'NON_ASCII']['Team'].unique()
print(f'Non-ASCII Team names ({len(non_ascii)} unique):')
for t in sorted(non_ascii)[:30]:
    print(f'  [{t}]')

Team name character type distribution:
team_char_type
ASCII        252377
NON_ASCII       188
Name: count, dtype: int64

Non-ASCII Team names (3 unique):
  [Côte d'Ivoire]
  [São Tomé and Príncipe]
  [Türkiye]

## 9. Exact Duplicate Check

**Why**: PIPELINE.md Step 1.1.1 says duplicates are defined by (Name, NOC, Year, Event). Same athlete, same country, same year, same event appearing twice = recording error. We need to know how many duplicates exist before writing dedup logic.

In [14]:
dup_cols = ['Name', 'NOC', 'Year', 'Event']
dup_mask = df.duplicated(subset=dup_cols, keep=False)
n_dup_rows = dup_mask.sum()

n_dup_groups = df[dup_mask].groupby(dup_cols).ngroups if n_dup_rows > 0 else 0

print(f'Exact duplicate rows (on {dup_cols}): {n_dup_rows:,}')
print(f'Duplicate groups: {n_dup_groups:,}')
print()

if n_dup_rows > 0:
    print('=== Sample of duplicate groups ===')
    display(df[dup_mask].sort_values(dup_cols).head(12))
else:
    print('No exact duplicates found.')

Exact duplicate rows (on ['Name', 'NOC', 'Year', 'Event']): 2,342
Duplicate groups: 773

=== Sample of duplicate groups ===

,Name,Sex,Team,NOC,Year,City,Sport,Event,Medal,team_char_type
76004,A. Dubois,M,Gitana-2,FRA,1900,Paris,Sailing,Sailing Mixed 3-10 Ton,Bronze,ASCII
76005,A. Dubois,M,Gitana-2,FRA,1900,Paris,Sailing,Sailing Mixed 3-10 Ton,Silver,ASCII
95608,A. Rogers,M,Great Britain,GBR,1948,London,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",No medal,ASCII
95609,A. Rogers,M,Great Britain,GBR,1948,London,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",No medal,ASCII
55948,Aase -hoffman-madsen),F,Denmark,DEN,1924,Paris,Art Competitions,Art Competitions Mixed Painting,No medal,ASCII
55949,Aase -hoffman-madsen),F,Denmark,DEN,1924,Paris,Art Competitions,Art Competitions Mixed Painting,No medal,ASCII
7,Abdul Assar,M,Afghanistan,AFG,1948,London,Football,Football Men's Football,No medal,ASCII
8,Abdul Assar,M,Afghanistan,AFG,1948,London,Football,Football Men's Football,No medal,ASCII
177623,Abdul Khan,M,Pakistan,PAK,1948,London,Hockey,Hockey Men's Hockey,No medal,ASCII
177625,Abdul Khan,M,Pakistan,PAK,1948,London,Hockey,Hockey Men's Hockey,No medal,ASCII
232245,Acee Eagle,M,United States,USA,1932,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",No medal,ASCII
232246,Acee Eagle,M,United States,USA,1932,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",No medal,ASCII

## 10. NOC Coverage Check

**Why**: Every NOC in athletes must appear in the medal_counts reference list (Step 1.1.4). NOCs in athletes but NOT in medal_counts are suspicious — possibly typos or historical codes. NOCs in medal_counts but NOT in athletes is also interesting — countries that won medals but have no athlete records?

In [15]:
from src.utils.config import MEDAL_COUNTS_FILE

medals_df = read_csv(MEDAL_COUNTS_FILE)

athlete_nocs = set(df['NOC'].dropna().unique())
medal_nocs = set(medals_df['NOC'].dropna().unique())

print(f'NOCs in athletes    : {len(athlete_nocs)}')
print(f'NOCs in medal_counts: {len(medal_nocs)}')
print()

only_athletes = athlete_nocs - medal_nocs
only_medals = medal_nocs - athlete_nocs
common = athlete_nocs & medal_nocs

print(f'NOCs in BOTH         : {len(common)}')
print(f'NOCs only in athletes: {len(only_athletes)}')
print(f'NOCs only in medals  : {len(only_medals)}')
print()

if only_athletes:
    print(f'NOCs only in athletes (flag for review):')
    for noc in sorted(only_athletes):
        teams = df[df['NOC'] == noc]['Team'].unique()
        print(f'  {noc}: {list(teams)}')

if only_medals:
    print(f'\nNOCs only in medal_counts (check if expected):')
    for noc in sorted(only_medals):
        print(f'  {noc}')

NOCs in athletes    : 234
NOCs in medal_counts: 210

NOCs in BOTH         : 1
NOCs only in athletes: 233
NOCs only in medals  : 209

NOCs only in athletes (flag for review):
  AFG: ['Afghanistan']
  AHO: ['Netherlands Antilles']
  AIN: ['AIN']
  ALB: ['Albania']
  ALG: ['Algeria']
  AND: ['Andorra']
  ANG: ['Angola']
  ANT: ['Antigua and Barbuda']
  ANZ: ['Australasia', 'Sydney Rowing Club']
  ARG: ['Argentina', 'Matrero II', 'Blue Red', 'Argentina-2', 'Pampero', 'Wiking', 'Cupidon III', 'Arcturus', 'Covunco III', 'Tango', 'Argentina-1', 'Acturus', 'Antares', 'Mizar', 'Gullvinge', 'Djinn', 'Rampage', 'Ardilla']
  ARM: ['Armenia']
  ARU: ['Aruba']
  ASA: ['American Samoa']
  AUS: ['Australia', 'Australia-2', 'Australia-1', 'Relampago', 'Buraddoo', 'Gabbiano', 'Vinha', 'Paula', 'Cambria', 'Diablo', 'Naiad', 'Pakaria', 'Moorina', 'Australia/Great Britain', 'Hornet', 'Australia-3', 'Barrenjoey', 'Quando Quando', 'Maryke', 'Falcon VI', 'Amateur Athletic Association', 'Greenoaks Dundee', 'Falcon IV']
  AUT: ['Austria', 'Breslau', 'Evita VI', 'Austria-1', 'R.-V. Germania, Leitmeritz', 'Austria-2', 'May-Be 1960', '30. Februar', 'Brigantia', 'Surprise', 'Philadelphia Turngemeinde, Philadelphia', 'Donar III']
  AZE: ['Azerbaijan']
  BAH: ['Bahamas', 'Gem', 'Guanahani', 'Gem III', 'Gem IV', 'Gem VII', 'Yeoman', 'John B', 'Bim', 'Combine']
  BAN: ['Bangladesh']
  BAR: ['Barbados']
  BDI: ['Burundi']
  BEL: ['Belgium', 'Dolfijn', 'Suzy-2', 'Royal Club Nautique de Gand', 'Edelweiss II-1', 'Antwerpia V', 'Belgium-1', 'Brussels Swimming and Water Polo Club', 'Belgium-2', 'Meteor', 'Belgium-4', 'Girl Pat', 'Univ. of Brussels', 'Ubu', 'Lalage', 'Freddy', 'Belgium-3', 'Pupilles de Neptune de Lille #1-3', 'Zut', 'Tan-Fe-Pah', 'Ciss', 'Danzig']
  BEN: ['Benin']
  BER: ['Bermuda', 'Oleander XII', 'Bermudes', 'Bermudian', 'Pam', 'Oleander II']
  BHU: ['Bhutan']
  BIH: ['Bosnia and Herzegovina', 'Bosnia & Herzegovina']
  BIZ: ['Belize']
  BLR: ['Belarus', 'Belarus-1', 'Belarus-2']
  BOH: ['Bohemia', 'Bohemia-1', 'Bohemia-3', 'Bohemia-2', 'Bohemia/Great Britain']
  BOL: ['Bolivia']
  BOT: ['Botswana']
  BRA: ['Brazil', 'Clementine V', 'Brazil-1', 'Brazil-2', 'Inca', 'Buscape II', 'Andorinha', 'Terrible', 'Bu III', 'Vento Sul', 'Lbeck', 'Escapade', 'Pimm']
  BRN: ['Bahrain']
  BRU: ['Brunei', 'Brunei Darussalam']
  BUL: ['Bulgaria', 'Bulgaria-2', 'Bulgaria-1']
  BUR: ['Burkina Faso']
  CAF: ['Central African Republic', 'Centr Afric Re']
  CAM: ['GyoshuII', 'Cambodia']
  CAN: ['Canada', 'Mohawk Indians-2', 'Toronto Argonauts', 'Argonaut Rowing Club', 'Canada-1', 'Canada-2', 'Winnipeg Shamrocks-1', 'Serendipity', 'Caprice', 'Trickson VI', 'Gran Gesto', 'Scram', 'Beaver', 'Galt Football Club', 'SagaII', 'Santa Maria', 'Mad Dog', 'Dresden', 'Ariel', 'Jet', 'Syndi', 'Tomahawk II', 'Whirlaway', 'Argo II', 'State VI', 'Glisten', 'Pop Art', 'Manana', 'Orion', 'Scaup', 'Windor']
  CAY: ['Cayman Islands']
  CGO: ['Congo (Brazzaville)', 'Republic of the Congo', 'Congo']
  CHA: ['Chad']
  CHI: ['Chile', 'Mainz']
  CHN: ['China', 'China-2', 'China-1', 'China-3']
  CIV: ["Cote d'Ivoire", 'Ivory Coast', "Côte d'Ivoire"]
  CMR: ['Cameroon']
  COD: ['Congo (Kinshasa)', 'Democratic Republic of the Congo', 'DR Congo']
  COK: ['Cook Islands']
  COL: ['Colombia', 'Racing Club de France']
  COM: ['Comoros']
  CPV: ['Cape Verde', 'Cabo Verde']
  CRC: ['Costa Rica']
  CRO: ['Croatia']
  CRT: ['Crete']
  CUB: ['Cuba', 'Hatuey', 'Cuba-1', 'Kurush IV', 'Vesania', 'Kurush II', 'Cuba-2']
  CYP: ['Cyprus']
  CZE: ['Czech Republic', 'Czech Republic-2', 'Czech Republic-1', 'Czechia']
  DEN: ['Denmark', 'Denmark/Sweden', 'Nykjbings paa Falster', 'Tip', 'Denmark-2', 'Denmark-1', 'Snap', 'Dansk Idrts Forbund', 'Anitra', 'Snude', 'White Lady', 'Web II', 'Web III', 'Chok', 'Polyteknisk Roklub-1', 'Jill', 'Kiel', 'Morena', 'Bonzo', 'Roklubb Kbnhavn-2', 'Skum', 'Miss Denmark 1964', 'Denmark-3', 'Don Schufro', 'Nurdug II', 'Clearwater', 'Denmark-4', 'Hi-Hi', 'Digby']
  DJI: ['Djibouti']
  DMA: ['Dominica']
  DOM: ['Dominican Republic']
  ECU: ['Ecuador']
  EGY: ['Egypt']
  EOR: ['Refugee Olympic Team', 'EOR']
  ERI: ['Eritrea']
  ESA: ['El Salvador']
  ESP: ['Spain', 'Galerna', 'Spain-2', 'Tajamar', 'Spain-1', 'Amolgavar', 'Posillipo III', 'Ral-Club Barcelona', 'Fruits', 'Pasodoble', 'Canopus']
  EST: ['Estonia', 'Tutti V', 'Brandenburg']
  ETH: ['Ethiopia']
  EUN: ['Unified Team', 'Unified Team-1', 'Unified Team-2']
  FIJ: ['Fiji']
  FIN: ['Finland', 'Lucky Girl-1', 'Heatherbell', 'rn-2', 'Nina', 'Teresita', 'Rififi', 'Bella', 'Inga-Lill XXXXIII', 'Finn II', 'Tu-Fri', 'Chaje II', 'Xantippa', 'Helsingfors R. K.', 'Finland-1', 'Finland-2', 'Sheerio', 'Raili', 'Vinha', 'Lucky Star', 'Ralia', 'Lynn', 'Bremen', 'Squid III']
  FRA: ['France', 'France-1', 'Union des Socits Franais de Sports Athletiques', 'France-3', 'Martha-27', 'Martha-1', 'Socit Nautique de Bayonne', 'Cupidon Viking', 'Damoiselle', 'USFSA', 'Club Nautique de Dieppe-5', 'EA II', 'Guyoni', 'Carabinier-5', 'Pettit-Poucet-6', 'Carabinier-15', 'Racing Club de France', 'Crabe II-12', 'Nina Claire-30', 'Crabe II-1', 'Crabe II-4', 'Nina Claire-2', "Qu'Importe", 'France-2', 'Socit Nautique de Bayonne-2', 'Socit Nautique de Bayonne-1', 'Tritons Lillois-2', 'Club Nautique de Franais-1', 'Esterel-1', 'Olle', 'Whitini Star', "L'Aile VI", "Cercle de l'Aviron Roubaix-4", 'Compigne Polo Club', 'Namoussa', 'Pigoule', 'Snowten III', 'LaBandera', 'Gilliatt V', 'Sarcelle-35', 'Sarcelle-3', 'Pupilles de Neptune de Lille #2-1', 'Societ Nautique de la Marne', 'Eissero VI', 'Allegro', 'Gam II', 'Quand-Mme-33', 'Quand-Mme-2', 'Calimucho', 'Libellule de Paris', 'Libellule de Paris-3', 'Societ Nautique de la Marne-3', 'Chicago Athletic Association', 'Calypse II', 'Tournade-40', 'Tornade-16', 'Rozenn-3', 'Plume-patte-32', 'Plume-Patte-5', 'Pierre et Jean-3', 'Pierre et Jean-4', 'Sidi Fekkar-36', 'Sidi-Fekkar-14', 'Souvenance', 'Crabe I-11', 'Crabe I-3', 'Crabe I-2', 'Gwendoline-22', 'Gwendoline-2', 'Virginie', 'BLO Polo Club, Rugby', 'Fada', 'Bagatelle Polo Club, Paris', 'United States/France', 'Socit Nautique de la Basse Seine-1', 'Socit Nautique de la Basse Seine-2', 'Rowing Club Castillon-3', 'Frip IV', 'Hb-24', 'Hb-20', 'Mignon-29', 'Mignon-3', 'Favorite-17', 'Favorite-1', 'Gitana-21', 'Gitana-2', 'Galopin-20', 'Galopin-9', 'France-4', 'Pupilles de Neptune de Lille #1-3', 'Cercle Nautique de Reims-4', 'Kannibaltje', 'Cinara-13', 'Baby-9', 'Baby-1', 'Femur-18', 'Femur-1', 'Smyrna', 'Colette-10', 'Colette-12', 'Tramontane', 'Sandra', 'Dick-8', 'Amulet-7', 'Amulet-3', 'Crocodile-13', 'Crocodile-11', 'Leipzig', 'Red Indian', 'Alcyon-6', 'Alcyon-7', 'Suzon IV-39', 'Suzon IV-5', 'Mascaret-28', 'Mascaret-4', 'Pupilles de Neptune de Lille-1', 'Aloha II', 'Stade Franais AC-2', 'Club Nautique de Lyon-2', 'Gyp-23', 'Gyp-6', 'Pirouette-31', 'Pirouette-5', 'Societ Nautique de la Marne-1', 'Scamasaxe-34', 'Scamasaxe-2', 'Scamasaxe-3', 'Jeanette-25', 'Jeannette-18', 'Turquoise-1', 'Turquoise-3', 'Ducky-16', 'Ducky-4', 'Rose Pompon', 'Souriceau-38', 'Souriceau-4', 'Marsouin-26', 'Marsouin-8', 'Diabolo St Maurice', 'Astrid III', 'Demi-Mondaine-15', 'Demi-Mondaine-17', 'France/Great Britain', 'Verveine-41', 'Verveine-19', 'Ariette-8', 'Ariette-10', 'Fantlet-2', 'Fantlet-7', 'Giselle-6', 'Mamie-4', 'C.V.A.-14', 'Singy-37', 'C.V.A.-7', 'Mamie-6', 'Singy-7', 'Mac Miche', 'Camille', 'Freia-19', 'Freia-5']
  FRG: ['West Germany', 'West Germany-1', 'West Germany-2', 'West Germany-3']
  FSM: ['Federated States of Micronesia', 'Micronesia']
  GAB: ['Gabon']
  GAM: ['Gambia', 'The Gambia']
  GBR: ['Great Britain', 'Yeoman VII', 'Yeoman XII', 'Great Britain-1', 'Ireland-2', 'Union des Socits Franais de Sports Athletiques', 'Great Britain-2', 'Hera-1', 'Wolseley-Siddeley-1', 'Bluebottle', 'England-1', 'Fortuna', 'Starlight III', 'Leander Club-2', 'London City Police-1', 'Great Britain-3', 'Sabre', 'Mouchette-2', 'Moseley Wanderers', 'Devon and Somerset Wanderers', 'Mistral Hojris', 'Lalage', 'Amateur Athletic Association', 'Foxhunters Hurlingham', 'Thames Rowing Club', 'Heroine', 'Chuckles', 'Great Britain/Germany', 'Swift', 'New College, Oxford-2', 'Vision', 'Cambridge University Boat Club-2', 'Lucky Star', 'Ceres II', 'Upton Park FC', 'BLO Polo Club, Rugby', 'Hurlingham-2', 'Leander Club-1', 'Libellule de Paris', 'Scotland-3', 'Liverpool Police Team-2', 'Brynhild-2', 'Cobweb-1', 'K Division Metropolitan Police Team-3', 'Smyrna', 'Osborne Swimming Club, Manchester', 'Ancora', 'Saskia', 'Wales-4', 'Scotland', 'Scotland-2', 'Great Britain-4', 'Dormy-1', 'Magdalen College Boat Club-1', 'Scotia', 'England', 'Cornwall', 'Beaver', 'Unique', 'United States/Great Britain', 'Ireland', 'Ireland-3', 'Olle', 'Leander Club #2-2', 'Feo', 'Gem II', 'Leander Club #1-1', 'Dylan-2', 'Gyrinus-1', 'Emily', 'Bagatelle Polo Club, Paris', 'Quicksilver-2', 'Paka', 'Salamander', 'Johan', 'Andromeda', 'Brat', 'Lancet', 'Bona Fide', 'Laurea-1', 'Sorais-2', 'Joy', 'Sibindi-2', 'France/Great Britain', 'Nan-2', 'Roehampton-1', 'Twinkle', 'Lady C', 'Titia', 'Cicely-1', 'Australia/Great Britain', 'Potsdam', 'Univ. of Brussels', 'Bohemia/Great Britain', 'Sea Dog-2', 'Omilos Ereton Smyrnis']
  GBS: ['Guinea Bissau', 'Guinea-Bissau']
  GDR: ['East Germany', 'East Germany-1', 'East Germany-3', 'East Germany-2']
  GEO: ['Georgia']
  GEQ: ['Equatorial Guinea']
  GER: ['Germany', 'Germany-1', 'Mutafo', 'Favorite Hammonia-3', 'Frankfurt Club', 'Ludwigshafener Ruderverein', 'Bronia', 'Germany-2', 'Berliner Ruderverein von 1876-2', 'Dinah V', 'Tom Kyle', 'Tilly', 'Germania II', 'Wannsee', 'Aschenbrodel', 'Elvis Va', 'Berliner Ruderclub Sport-Borussia-1', 'Gustel V', 'South St Louis Turnverein, St Louis', 'Berliner Ruderclub', 'Nirwana', 'Ludwigshafener Ruder Verein-1', 'Paka V', 'Tantalus', 'Germania Ruder Club, Hamburg', 'Germania Ruder Club, Hamburg-2', 'Deutscher Schwimm Verband Berlin', 'Germany/United States', 'Turnverein Vorwrts, Chicago', 'Germany-3', 'Pan', 'Macky VI', 'Bonaparte', 'Subbnboana', 'Rostock', 'St. Louis Southwest Turnverein #2-3', 'Bellatrix IX', 'Bellatrix XIII', 'Wendehals', 'Gustel X', 'Gustl XI', 'Great Britain/Germany', 'Satchmo']
  GHA: ['Ghana']
  GRE: ['Greece', 'Thessalonki-1', 'Large boat, Central Naval Prep School "Poros"-1', 'Greece-3', 'Lemzos Thorichton "Spetsai"-4', 'Greece-1', 'Greece-2', 'Nautikos Omilos-3', 'Life boat naval ship "Spetsai"-1', 'Lemzos Thorichton "Psara"-3', 'Nikh', 'Athens-2', 'Panhellenios Gymnastikos Syllogos-1', 'Pan-Hellenic Athletic Club', 'Phalainis ton Thorichtou "Hydra"-2', 'Omilos Ereton Peiraios-2', 'Nirefs', 'Proteus II', 'Peiraikos Syndesmos-2', 'Omilos Ereton Smyrnis', 'Nephos I', 'Ethnikos Gymnastikos Syllogos', 'Phalainis ton Thorichtou "Psara"-3', 'Olympion', 'Omas Helliniki P. S.', 'Zefyros', 'Royal Club Nautique de Gand', 'Marie-Tim', 'Greece-4']
  GRN: ['Grenada']
  GUA: ['Guatemala']
  GUI: ['Guinea']
  GUM: ['Guam']
  GUY: ['Guyana']
  HAI: ['Haiti', 'Union des Socits Franais de Sports Athletiques']
  HKG: ['Hong Kong', 'Hong Kong-1', 'Phoenix', 'Hong Kong-2', 'Hong Kong, China']
  HON: ['Honduras']
  HUN: ['Hungary', 'Hungaria Evezos Egylet', 'Hungaria', 'Hungary-1', 'Pannonia RC/National RC', 'Hungary-2', 'Knigsberg', 'Balaton', 'Olimpia', 'Hungary-3']
  INA: ['Indonesia', 'Indonesia-1', 'Indonesia-2', 'Partenope', 'Tengiri']
  IND: ['India', 'India-1', 'India-2']
  IOA: ['Individual Olympic Athletes']
  IRI: ['Iran', 'IR Iran']
  IRL: ['Ireland', 'The Cloud', 'Aletta', 'Ireland-2', 'Akatonbo', 'Three Leaves', 'Ireland-1']
  IRQ: ['Iraq']
  ISL: ['Iceland']
  ISR: ['Israel']
  ISV: ['United States Virgin Islands', 'Virgin Islands', 'Virgin Islands, US']
  ITA: ['Italy', 'Roma', 'Ciocca II', 'Mirtala', 'Marinai della nave da guerra "Varese"', 'Pistoja/Firenze', 'Italia', 'Ausonia', 'Italy-1', 'Bucintoro Venezia-1', 'Bucintoro Venezia', 'Bamba', 'Twins II', 'Romolo', 'Aldebaran II', 'Aldebaran', 'Italy-2', 'Galatea II', 'Twins VIII', 'Barion/Bari-2', 'Venilia', 'Ciocca', 'Esperia', 'Umberta V', 'Pegaso', 'Augsburg', 'Argeste', 'Aretusa', 'Mebi', 'Grifone', 'Voloira II', 'Legionario', 'Merope', 'Merope III', 'Enotria']
  IVB: ['British Virgin Islands', 'Virgin Islands, B']
  JAM: ['Jamaica', 'Miss Nippon IV']
  JOR: ['Jordan']
  JPN: ['Japan', 'Japan-1', 'Japan-2', 'Essen', 'Miss Nippon V', 'Roy', 'Whisper', 'Boreas', 'MitaII', 'Rambo', 'Riccar', 'Japan-3', 'Myojo', 'Danaldo', 'Dow Jones']
  KAZ: ['Kazakhstan']
  KEN: ['Kenya']
  KGZ: ['Kyrgyzstan']
  KIR: ['Kiribati']
  KOR: ['South Korea', 'South Korea-2', 'South Korea-1', 'Korea']
  KOS: ['Kosovo']
  KSA: ['Saudi Arabia']
  KUW: ['Kuwait']
  LAO: ['Laos', 'Lao PDR']
  LAT: ['Latvia', 'Latvia-1', 'Latvia-2']
  LBA: ['Libya']
  LBN: ['Lebanon']
  LBR: ['Liberia']
  LCA: ['Saint Lucia']
  LES: ['Lesotho']
  LIB: ['Lebanon', 'Maid of Lebanon']
  LIE: ['Liechtenstein']
  LTU: ['Lithuania']
  LUX: ['Luxembourg']
  MAD: ['Madagascar']
  MAL: ['Malaya']
  MAR: ['Morocco']
  MAS: ['Malaysia', 'Malaysia-1', 'Malaysia-2']
  MAW: ['Malawi']
  MDA: ['Moldova', 'Republic of Moldova']
  MDV: ['Maldives']
  MEX: ['Mexico', 'Xolotl', 'Chamukina', 'Nausikaa 4', 'Acipactli', 'A North American Team', 'Tlaloc']
  MGL: ['Mongolia']
  MHL: ['Marshall Islands']
  MKD: ['Macedonia', 'North Macedonia']
  MLI: ['Mali']
  MLT: ['Malta', 'Merope']
  MNE: ['Montenegro']
  MON: ['Monaco', 'Hirondelle', 'Damoiselle IV']
  MOZ: ['Mozambique']
  MRI: ['Mauritius', 'Mauritius-2', 'Mauritius-1']
  MTN: ['Mauritania']
  MYA: ['Myanmar', 'Kingfisher', 'Yangon']
  NAM: ['Namibia']
  NBO: ['North Borneo']
  NCA: ['Nicaragua']
  NED: ['Netherlands', 'Boreas-2', 'Netherlands-2', 'Minerva Amsterdam', 'Netherlands-1', 'Amstel Amsterdam', 'Oranje', 'Willem-Six', 'DeRuyter', 'Daisy', 'Bem II', 'St. Margrite', 'Hollandia', 'Joy', 'Thalatta', 'Trintel II', 'Kemphaan', 'Beatrijs III-1', 'Mascotte', 'Barco Deloro', 'Nrnberg', 'Holland', 'Starita', 'Nadine', 'Sunrise', 'Salinero', 'Univ. of Brussels']
  NEP: ['Nepal']
  NFL: ['Newfoundland']
  NGR: ['Nigeria', 'Nigeria-2', 'Nigeria-1']
  NIG: ['Niger']
  NOR: ['Norway', 'Taifun', 'Fornebo', 'Stella-2', 'Heira II', 'Lett', 'Norway-1', 'Norna', 'Fram', 'Magda IX', 'Mosk II', 'Elisabeth X', 'Pan', 'Nora', 'Monica', 'Sirene', 'Atlanta', 'Norway-2', 'Norway-3', 'Kristiania Roklub-1', 'Kristiania Roklub', 'Ormsund Roklub-2', 'Bera', 'Jo', 'Norwegian Rowing Association', 'Sonja II', 'KNS', 'Elisabeth V', 'Studenternes Roklub-2', 'Viking', 'Silja', 'Marmi II-1', 'Apache', 'Encore', 'Struten', 'Fram III', 'Pan II', 'Eleda', 'Irene', 'Lucky', 'Lully II', 'Sildra-1', 'Noreg', 'Norwegier Turnverein, Brooklyn', 'Lyn-2', 'Hamburg']
  NRU: ['Nauru']
  NZL: ['New Zealand', 'Jest', 'Red Dragon', 'Osborne Swimming Club, Manchester', 'Pandora', 'Harmony']
  OMA: ['Oman']
  PAK: ['Pakistan']
  PAN: ['Panama']
  PAR: ['Paraguay']
  PER: ['Peru']
  PHI: ['Philippines', 'Patricia', 'Kalayaan']
  PLE: ['Palestine']
  PLW: ['Palau']
  PNG: ['Papua New Guinea']
  POL: ['Poland', 'Poland-1', 'Poland-2', 'Poland-3', 'Danuta']
  POR: ['Portugal', 'Grifo III', 'Grifo IV', 'Symphony', 'Sjhxa', 'Faneca', 'Ciocca III', 'Camelia', 'Calcinhas', 'Argus', 'Espadarte', 'Canopus', 'Vicking', 'Oxalis', 'Espardate', 'Alcaid', 'Hannover', 'Notavel', 'Galopin De La Font', "Ma'Lindo"]
  PRK: ['North Korea', 'North Korea-1', 'North Korea-2', 'DPR Korea']
  PUR: ['Puerto Rico']
  QAT: ['Qatar']
  RHO: ['Rhodesia', 'Peri']
  ROT: ['Refugee Olympic Athletes']
  ROU: ['Romania', 'Romania-2', 'Romania-1']
  RSA: ['South Africa', 'Shoveller', 'South Africa-2', 'Impala', 'Springbok', 'Yeoman V', 'Boer Team', 'South Africa-1', 'Hakahana']
  RUS: ['Russia', 'Bylina-2', 'Russia-2', 'Gallia II', 'Russia-1', 'Norman-1']
  RWA: ['Rwanda']
  SAA: ['Saar']
  SAM: ['Samoa']
  SCG: ['Serbia and Montenegro']
  SEN: ['Senegal']
  SEY: ['Seychelles']
  SGP: ['Singapore', 'June Climene', 'Rika II', 'Singapore-2', 'Singapore-1']
  SKN: ['Saint Kitts and Nevis', 'St Kitts and Nevis']
  SLE: ['Sierra Leone']
  SLO: ['Slovenia', 'Slovenia-1', 'Slovenia-2']
  SMR: ['San Marino']
  SOL: ['Solomon Islands']
  SOM: ['Somalia']
  SRB: ['Serbia', 'Serbia-2', 'Serbia-1']
  SRI: ['Sri Lanka']
  SSD: ['South Sudan']
  STP: ['Sao Tome and Principe', 'São Tomé and Príncipe', 'Sao Tome & Principe']
  SUD: ['Sudan']
  SUI: ['Switzerland', 'Switzerland-1', 'Switzerland-2', 'Ali-Baba II', 'Ali-Baba IV', 'Ali-Baba VI', 'Ali-Baba IX', 'Fantasio III', 'Pousse-Moi Pas VII', 'Baccara', 'Ylliam VIII', 'Tim-Tam III', 'Ylliam VII', 'Ballerina IV', 'Lerina', 'Ylliam II', 'Alain IV', 'Kln']
  SUR: ['Suriname']
  SVK: ['Slovakia', 'Slovakia-2', 'Slovakia-1']
  SWE: ['Sweden', 'Gteborgs Roddklubb-1', 'Bissbi', 'Tornado', 'Elsie', 'Ali-Baba II', 'May Be VII', 'Sweden-1', 'Sweden-2', 'Sweden-3', 'Swedish Star', 'Kerstin-1', 'Kullan', 'Erna Signe', 'Slaghoken', 'Slaghoken II', 'Marga-2', 'Gteborgs Roddfrening-2', 'Briar', 'Roddklubben af 1912-1', 'Roddklubben af 1912-2', 'Lotta IV', 'Saga-2', 'Mari', 'Galejan', 'May Be', 'Kitty-1', 'Vaxholm Roddklubb', 'Ilderim', 'K.S.S.S. 1912-2', 'Freja', 'Sass-2', 'Sylvia', 'Ingegerd', 'Sweden-4', 'Chance', 'Vinga-1', 'Aloha II', 'Sans Atout-1', 'Kuling', 'Sif', 'Hayama', 'Rush VII', 'Rush V', 'Floresco', 'Sunshine', 'Denmark/Sweden', 'Hojwa', 'Humbug V', 'Lasha', 'Sjovinge', 'Solos Carex']
  SWZ: ['Swaziland', 'Eswatini']
  SYR: ['Syria']
  TAN: ['Tanzania']
  TCH: ['Czechoslovakia', 'Czechoslovakia-3', 'Czechoslovakia-1', 'Czechoslovakia-2']
  TGA: ['Tonga']
  THA: ['Thailand', 'Linglom', 'Tichiboo', 'Siames-Cat', 'Thailand-1', 'Thailand-2']
  TJK: ['Tajikistan']
  TKM: ['Turkmenistan']
  TLS: ['Timor Leste', 'East Timor', 'Timor-Leste']
  TOG: ['Togo']
  TPE: ['Chinese Taipei-1', 'Chinese Taipei', 'Chinese Taipei-2']
  TTO: ['Trinidad and Tobago', 'Firebird II']
  TUN: ['Tunisia']
  TUR: ['Turkey', 'Marmara', 'Cuxhaven', 'Türkiye']
  TUV: ['Tuvalu']
  UAE: ['United Arab Emirates', 'UA Emirates']
  UAR: ['United Arab Republic']
  UGA: ['Uganda']
  UKR: ['Ukraine', 'Ukraine-2', 'Ukraine-1']
  UNK: ['Unknown']
  URS: ['Soviet Union', 'Burevestnik', 'Druzhba', 'Olen', 'Uragan', 'Kon-Tiki', 'Korshun', 'Viktoriya', 'Neptun II', 'Persey', 'Nokaut II', 'Almaz', 'Tulilind', 'Tornado', 'Taifun']
  URU: ['Uruguay', 'Nortazo', 'Bajazzo', 'Heidelberg']

## 11. Sport & Event Granularity

**Why**: Understanding how many unique Sports and Events exist helps validate against `summerOly_programs.csv`. Also reveals whether Event names are consistent across years.

In [16]:
print(f'Unique Sports : {df["Sport"].nunique()}')
print(f'Unique Events : {df["Event"].nunique()}')
print()

print('=== Top 15 Sports by unique event count ===')
sport_events = df.groupby('Sport')['Event'].apply(lambda x: x.nunique()).sort_values(ascending=False)
display(sport_events.head(15))

Unique Sports : 76
Unique Events : 1041

=== Top 15 Sports by unique event count ===

Sport
Athletics           137
Shooting             99
Swimming             98
Sailing              58
Rowing               51
Wrestling            48
Cycling              44
Weightlifting        41
Boxing               41
Archery              34
Fencing              30
Judo                 30
Art Competitions     29
Canoeing             27
Gymnastics           27
Name: Event, dtype: int64

## 12. City Column Quick Check

**Why**: The City field should match `summerOly_hosts.csv`. Quick check for any Year-City mismatches or unusual values.

In [17]:
print(f'Unique City values: {df["City"].nunique()}')
print()
print('=== City x Year combinations (sample) ===')
city_year = df.groupby('Year')['City'].first().reset_index()
display(city_year)

Unique City values: 23

=== City x Year combinations (sample) ===

    Year            City
0   1896          Athina
1   1900           Paris
2   1904       St. Louis
3   1906          Athina
4   1908          London
..   ...             ...
26  2008         Beijing
27  2012          London
28  2016  Rio de Janeiro
29  2020           Tokyo
30  2024           Paris

[31 rows x 2 columns]

## 13. Summary — Issues Found

After running all checks above, summarize findings here. Each issue should map to a specific step in `clean_athletes.py`:

| # | Issue | Severity | Maps to Step |
|---|-------|----------|--------------|
| 1 | (fill in after running) | | |
| 2 | ... | | |

This summary becomes the implementation checklist for Phase 1.